import{a as f,S as g,i as u}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const h="42651911-b9e9cf23b752713c606cec899",L="https://pixabay.com/api/";async function y(a,t){const r=new URLSearchParams({key:h,q:a,image_type:"horizontal",safesearch:"true",orientation:"horizontal",per_page:15,page:t});return(await f.get(`${L}?${r}`)).data}function m(a){const t=document.querySelector(".gallery-container"),r=a.hits.map(s=>`<div class="gallery-item">
    <a class="gallery-link" href="${s.largeImageURL}">
    <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
    </a>
    <div class="gallery-info">
    <p class="gallety-info-item"><span class="gallery-item-text">Likes:</span>${s.likes}</p>
    <p class="gallety-info-item"><span class="gallery-item-text">Views:</span>${s.views}</p>
    <p class="gallety-info-item"><span class="gallery-item-text">Comments:</span>${s.comments}</p>
    <p class="gallety-info-item"><span class="gallery-item-text">Downloads:</span>${s.downloads}</p>
    </div>
      </div>`).join("");t.innerHTML=r}const p=document.querySelector(".gallery-container"),i=document.querySelector(".form-input"),v=document.querySelector(".form"),l=document.querySelector(".load-button");let c=1;const b=15,w=Math.ceil(100/b);l.style.display="none";const d=new g(".gallery-link",{captionsData:"alt",captionDelay:250});v.addEventListener("submit",async function(a){a.preventDefault(),p.innerHTML='<span class="loader"></span>';const t=i.value.trim();if(l.style.display="block",t!=="")try{const r=await y(t,1);m(r),d.refresh(),c=1}catch(r){console.log(r)}else p.innerHTML="",u.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});i.value=""});l.addEventListener("click",async()=>{if(c>w)return u.error({position:"topRight",message:"We're sorry, there are no more posts to load"});try{const a=i.value.trim(),t=c+1,r=await y(a,t);m(r),d.refresh()}catch(a){console.log(a)}});
//# sourceMappingURL=commonHelpers.js.map
